MODULE m_cpu

! list des opcodes :
! NOP, RESET, HALT 
! OR, XOR, NOT, LESS, LESSU, LEQ, LEQU, EQL, EQLU, NEQ,  NEQU
! GEQ, GEQU, GTR, GTRU, LSHIFT, RSHIFT, CMP, INC, DEC
! MOV, PUSH, PPOP, POPCNT, JMP

    ! MATH
    ! ADD, SUB, MUL, DIV, MOD, ABS, MIN, MAX, NEG, MAD

    ! STRING
    ! CMP, LOCATE, LENGHT
END MODULE