#
# Automagically generated by Approximatrix Simply Fortran 2.41
#
FC="D:\SimplyFortran2\mingw-w64\bin\gfortran.exe"
CC="D:\SimplyFortran2\mingw-w64\bin\gcc.exe"
AR="D:\SimplyFortran2\mingw-w64\bin\ar.exe"
WRC="D:\SimplyFortran2\mingw-w64\bin\windres.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -Og -mtune=native

SPECIALFLAGS=-m32 $(IDIR)

RCFLAGS=-O coff -F pe-i386

PRJ_FFLAGS=-ffast-math -floop-parallelize-all -ftree-parallelize-loops=4 -fcheck=all -std=f2008

PRJ_CFLAGS=

# Auto-including AppGraphics libraries.
PRJ_LFLAGS=-lappgraphics -lgdi32 -lcomdlg32 -lcomctl32 -luuid -loleaut32 -lole32

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\m_control.o": ".\m_control.f90"
	@echo Compiling .\m_control.f90
	@$(FC) -c -o "build\m_control.o" $(FFLAGS) ".\m_control.f90"
"modules\m_control.mod" : "build\m_control.o" .EXISTSONLY
	@echo Compiling .\m_control.f90
	@$(FC) -c -o "build\m_control.o" $(FFLAGS) ".\m_control.f90"

"build\m_cpu.o": ".\m_cpu.f90"
	@echo Compiling .\m_cpu.f90
	@$(FC) -c -o "build\m_cpu.o" $(FFLAGS) ".\m_cpu.f90"
"modules\m_cpu.mod" : "build\m_cpu.o" .EXISTSONLY
	@echo Compiling .\m_cpu.f90
	@$(FC) -c -o "build\m_cpu.o" $(FFLAGS) ".\m_cpu.f90"

"build\m_global.o": ".\m_global.f90"
	@echo Compiling .\m_global.f90
	@$(FC) -c -o "build\m_global.o" $(FFLAGS) ".\m_global.f90"
"modules\m_global.mod" : "build\m_global.o" .EXISTSONLY
	@echo Compiling .\m_global.f90
	@$(FC) -c -o "build\m_global.o" $(FFLAGS) ".\m_global.f90"

"build\m_memory.o": ".\m_memory.f90"
	@echo Compiling .\m_memory.f90
	@$(FC) -c -o "build\m_memory.o" $(FFLAGS) ".\m_memory.f90"
"modules\m_memory.mod" : "build\m_memory.o" .EXISTSONLY
	@echo Compiling .\m_memory.f90
	@$(FC) -c -o "build\m_memory.o" $(FFLAGS) ".\m_memory.f90"

"build\m_reg.o": ".\m_reg.f90"
	@echo Compiling .\m_reg.f90
	@$(FC) -c -o "build\m_reg.o" $(FFLAGS) ".\m_reg.f90"
"modules\m_reg.mod" : "build\m_reg.o" .EXISTSONLY
	@echo Compiling .\m_reg.f90
	@$(FC) -c -o "build\m_reg.o" $(FFLAGS) ".\m_reg.f90"

"build\main.o": ".\main.f90" "modules\m_global.mod" "modules\m_control.mod"
	@echo Compiling .\main.f90
	@$(FC) -c -o "build\main.o" $(FFLAGS) ".\main.f90"


"build\sf_default_resource.res": "build\sf_default_resource.rc"
	@echo Processing default resource
	@$(WRC) build\sf_default_resource.rc $(RCFLAGS) -o build\sf_default_resource.res

clean: .SYMBOLIC
	@echo Deleting build\m_control.o and related files
	@$(RM) "build\m_control.o" "modules\m_control.mod" "modules\m_control.smod"
	@echo Deleting build\m_cpu.o and related files
	@$(RM) "build\m_cpu.o" "modules\m_cpu.mod" "modules\m_cpu.smod"
	@echo Deleting build\m_global.o and related files
	@$(RM) "build\m_global.o" "modules\m_global.mod" "modules\m_global.smod"
	@echo Deleting build\m_memory.o and related files
	@$(RM) "build\m_memory.o" "modules\m_memory.mod" "modules\m_memory.smod"
	@echo Deleting build\m_reg.o and related files
	@$(RM) "build\m_reg.o" "modules\m_reg.mod" "modules\m_reg.smod"
	@echo Deleting build\main.o and related files
	@$(RM) "build\main.o"
	@echo Deleting default icon resource
	@$(RM) "build\sf_default_resource.res"
	@echo Deleting FortranMachine.exe
	@$(RM) "FortranMachine.exe"

"FortranMachine.exe":  "build\m_control.o" "build\m_cpu.o" "build\m_global.o" "build\m_memory.o" "build\m_reg.o" "build\main.o" "build\sf_default_resource.res" "build\FortranMachine.prj.target"
	@echo Generating FortranMachine.exe
	@$(FC) -o "FortranMachine.exe" -static -m32 -mwindows "build\m_control.o" "build\m_cpu.o" "build\m_global.o" "build\m_memory.o" "build\m_reg.o" "build\main.o" "build\sf_default_resource.res" $(LDIR) $(PRJ_LFLAGS)

all: "FortranMachine.exe" .SYMBOLIC

